### ISSUE TITLE
Singly Linked List

### ISSUE THREAD

**Issue by kituu02** [gdsc-gvp/DSA#104]
### cpp

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

Singly-linked list with operations
1.)insertion at the beginning, after a specific element, and ending 
2.)deletion from beginning, a specific element and ending 
3.)display

**Comment by deephunt3r** [comment]
Hey! some already made an PR in cpp! could  you please choose some other language

**Comment by kituu02** [comment]
Already some made an pr in cpp
