### ISSUE TITLE
Adding few searching and sorting Algorithms in Python.

### ISSUE THREAD

**Issue by Yaswanth14** [gdsc-gvp/DSA#12]
### Algorithm name
Hey, I would like to add **Linear search**.  Could you please assign me?

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

**Comment by deephunt3r** [comment]
could you please create 4 different issues for 4 different algorithms 😃. you can work on those algorithms.
Add your files in 

-  Searching folder
   -  linear search folder(create one)
