### ISSUE TITLE
Quick_sortAlgo in C++

### ISSUE THREAD

**Issue by Dinesh0602** [gdsc-gvp/DSA#18]
Quick sort Algorithm
I would to contribute Quick sort Algorithm in C++

C++

- [ ] C

- [x] C++
- [ ] Java
- [ ] Python

**Comment by Dinesh0602** [comment]
#19

**Comment by deephunt3r** [comment]
@Dinesh0602 Hey can you please first create an issue and then create pr
You need to add file in such way that 
- sorting folder
   - Quicksort folder(create it)
