### ISSUE TITLE
Linear Search Algo in C++

### ISSUE THREAD

**Issue by GantaNikhil** [gdsc-gvp/DSA#29]
### Programming language

- [x] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by deephunt3r** [comment]
You can make pr now

**Comment by AmanRana10** [comment]
Can i also contribute to this repo? @deephunt3r

**Comment by deephunt3r** [comment]
> Can i also contribute to this repo? @deephunt3r

yes! you can work in either c/java

**Comment by AmanRana10** [comment]
ok

**Comment by deephunt3r** [comment]
> @deephunt3r can I also contribute to this repo? @GantaNikhil can i do it in python language

Hey python already assigned to someone

**Comment by deephunt3r** [comment]
@AmanRana10 in which language your are working?
@akash-kumar44 choose the remaining language

**Comment by akash-kumar44** [comment]
@deephunt3r is java accepted?

**Comment by deephunt3r** [comment]
> @deephunt3r is java accepted?

yes! you can work in java

**Comment by akash-kumar44** [comment]
@deephunt3r so please assign this to me

**Comment by deephunt3r** [comment]
@akash-kumar44 pls create PR in java

**Comment by akash-kumar44** [comment]
@deephunt3r Sorry for the delay. Actually, There was something wrong with my git-bash. When I tried to push this code it was showing error.
but now it's working fine.
