### ISSUE TITLE
Adding BFS and DFS traversal in Graphs in c++

### ISSUE THREAD

**Issue by tom635** [gdsc-gvp/DSA#31]
### Algorithm name
Mention the Algorithm  which you want to add 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by deephunt3r** [comment]
You can work on the issue now

**Comment by deephunt3r** [comment]
Make sure you create different folders in BFS folder

**Comment by tom635** [comment]
> Make sure you create different folders in BFS folder

ok
