### ISSUE TITLE
Binary Search Algo in C++

### ISSUE THREAD

**Issue by GantaNikhil** [gdsc-gvp/DSA#33]
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by deephunt3r** [comment]
Make sure you create a separate folder for binary search in Searching

**Comment by akash-kumar44** [comment]
@deephunt3r Can i Solve this In C language

**Comment by Sachin-Liyanage** [comment]
@GantaNikhil Can I Solve this In the Java language

**Comment by deephunt3r** [comment]
@Sachin-Liyanage you can work in java

**Comment by deephunt3r** [comment]
@akash-kumar44 you can work in C

**Comment by Gneya** [comment]
Can I solve it in C?

**Comment by pavinduLakshan** [comment]
@deephunt3r I'd like to work on this issue in Python, Please count me in 🙌

**Comment by deephunt3r** [comment]
@pavinduLakshan yes! you can work in py
