### ISSUE TITLE
Merge sort Algorithm

### ISSUE THREAD

**Issue by Dinesh0602** [gdsc-gvp/DSA#36]
### Merge sort
I wanna contribute Merge sort algorithm in C++
I will create a new folder(Merge sort) in sorting folder 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by akash-kumar44** [comment]
@Dinesh0602 can I work on this ?

**Comment by deephunt3r** [comment]
@Dinesh0602 you can start working on it

**Comment by akash-kumar44** [comment]
Ok

**Comment by deephunt3r** [comment]
> Ok

not you!
you can work in c/py/java

**Comment by akash-kumar44** [comment]
@deephunt3r I will work with c

**Comment by Dinesh0602** [comment]
OK @deephunt3r 
I will submit it within an hour
