### ISSUE TITLE
want to add a new question of merge k sorted arrays using priority queues

### ISSUE THREAD

**Issue by Naman1809** [gdsc-gvp/DSA#46]
[mergeksortedarrays.txt](https://github.com/gdsc-gvp/DSA/files/7267433/mergeksortedarrays.txt)
### Algorithm name
Mention the Algorithm  which you want to add 

### Programming language

- [ ] C
- [x] C+
- [ ] Java
- [ ] Python

**Comment by Naman1809** [comment]
want to add a new question and its solution 
the question is merge k sorted array and i want to solve it by priority queues

**Comment by deephunt3r** [comment]
Go and raise issue there https://github.com/gdsc-gvp/Problem-Solving
and Bot message doesn't mean to work on PR!
