### ISSUE TITLE
Bubble Sort 

### ISSUE THREAD

**Issue by akash-kumar44** [gdsc-gvp/DSA#52]
### Algorithm name
Mention the Algorithm  which you want to add 

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

**Comment by deephunt3r** [comment]
@akash-kumar44 We have assigned you so many issues, first work on them and then we will assign new issues

**Comment by akash-kumar44** [comment]
@deephunt3r I think I have sent the PR for all assigned issues. So, could you please assign this.

**Comment by deephunt3r** [comment]
you can work on it

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer in c language and recently i am pursuing b tech in computer science engeneering branch . (2 year)

**Comment by akash-kumar44** [comment]
Brother @Anjani87 If you want to do this in C language. Go ahead.
We will be happy if we could help you to start your coding journey.
And if you get stuck at any point. Feel free to ask
@deephunt3r assign this program for C lang. to @Anjani87 
I will submit it in Java and C++

**Comment by uzzal623** [comment]
Hi, can you assign me this. I want to do it.

**Comment by devpandhii** [comment]
please assign me this issue

**Comment by deephunt3r** [comment]
> please assign me this issue

please mention in which language you want add

**Comment by devpandhii** [comment]
> > please assign me this issue
> 
> please mention in which language you want add c/python

> > I'll do this sorting in both the languages if it's not an issue

**Comment by akash-kumar44** [comment]
@devpandhii brother Bubble sort in python is already merged and In c++, JAva i send PR's.
So the remaining language is C.
If you are comfortable with C then you can write algo in C

**Comment by AdithyaSanyal** [comment]
@deephunt3r Could you assign me this issue to write bubble sort algo in C

**Comment by deephunt3r** [comment]
Assigned!

**Comment by AdithyaSanyal** [comment]
@deephunt3r I have added the implementation of Bubble sort in C

**Comment by deephunt3r** [comment]
> @deephunt3r I have added the implementation of Bubble sort in C and have made a pull request

yes!

**Comment by Azmeerabhagyasree** [comment]
please assign me with bubble sort in c i will complete it

**Comment by Azmeerabhagyasree** [comment]
please assign me with binary search in c i will do it
