### ISSUE TITLE
Stacks Implementation

### ISSUE THREAD

**Issue by rnrathod16** [gdsc-gvp/DSA#62]
### Algorithm name
Mention the Algorithm  which you want to add 

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by deephunt3r** [comment]
@rnrathod16 someone already have created PR in cpp!
you can choose another lang

**Comment by rnrathod16** [comment]
@deephunt3r can i work on stack using linked list in the same repository

**Comment by deephunt3r** [comment]
yes!!
