### ISSUE TITLE
MaxPath Sum in Binary Tree

### ISSUE THREAD

**Issue by AbhinandanGautam** [gdsc-gvp/DSA#64]
### MaxPathSum in Binary Tree
Algorithm :
1. we travel recursively to leaf nodes of tree
2. declare a global variable max_ans
3. for each node we calculate 4 values 
      i. node value
      ii. node value + maxSumPath(node->left)
      iii. node value + maxSumPath(node->right)
      iv. node value + maxSumPath(node->left) + maxSumPath(node->right)
4. find maximum value among these 4 and if this value greater than max then put it there

### C++

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by AbhinandanGautam** [comment]
I am participating in Hacktober 2021

**Comment by AbhinandanGautam** [comment]
Please assign me this isssue

**Comment by deephunt3r** [comment]
Go and raise issue there https://github.com/gdsc-gvp/Problem-Solving
and Bot message doesn't mean to work on PR!
