### ISSUE TITLE
Queue implementation in Java 

### ISSUE THREAD

**Issue by batul02** [gdsc-gvp/DSA#75]
### Algorithm name
Queue Data Structure in Java.

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

### Additional context (OPTIONAL)
I would like to implement Queue data structure in the programming language Java. I want to contribute to open source and I am also a participant of hacktoberfest. It will be really helpful if this issue will be allocated to me.

**Comment by deephunt3r** [comment]
Assigned!
