### ISSUE TITLE
Heap sort 

### ISSUE THREAD

**Issue by nikhilvegulla** [gdsc-gvp/DSA#97]
### Algorithm name
Mention the Algorithm  which you want to add 
Heap Sort
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [X] Python

### Additional context (OPTIONAL)
sorting of elements in a array using heap sort algorithm (using min heap)

**Comment by deephunt3r** [comment]
Hey! create a new folder with name 
- Sorting
  - Heapsort
     - add your file in it

**Comment by KanishkKhurana** [comment]
@deephunt3r please assign C++ to me , 
i'd love to use my knowledge and contribute to your project
